apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote2-aoa
  namespace: nethopper
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/nethopper2/temp.git
    targetRevision: HEAD
    path: gitops/net1/remote2
  destination:
    server: https://kubernetes.default.svc
    namespace: nethopper
