apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote2-app2
  namespace: nethopper
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/nethopper2/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://nh-kapi-remote2:8080
    namespace: gb2
